// <auto-generated />
using System;
using CompetitionEventsManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompetitionEventsManager.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230115101618_withManyToManyRelationshipsUpdated")]
    partial class withManyToManyRelationshipsUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("CompetitionEventsManager.Models.Competition", b =>
                {
                    b.Property<int>("CompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdditionalTime")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArenaType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Article")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BreakTime")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompetitionType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EId")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfJumps")
                        .HasMaxLength(3)
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfObstackles")
                        .HasMaxLength(3)
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Phase")
                        .HasMaxLength(2)
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PointsForExeedindTimeLimit")
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecToStart")
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SheduledRunTime")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SheduledStartTime")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Time")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeAllowed")
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeBeetweenRuns")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CompetitionID");

                    b.HasIndex("EId");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            CompetitionID = 1,
                            AdditionalTime = 5,
                            ArenaType = "Maniezas",
                            Article = "Art.238.2.1 ",
                            BreakTime = 10,
                            Class = "ATVIRA KLASĖ",
                            CompetitionType = "lentelė A",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2017),
                            Number = "1A. ",
                            NumberOfJumps = 10,
                            NumberOfObstackles = 8,
                            Phase = 1,
                            PointsForExeedindTimeLimit = 1,
                            SecToStart = 45,
                            SheduledRunTime = 2,
                            TimeBeetweenRuns = 2,
                            Title = "Art.238.2.1 Konkūras pagal laiką, lentelė A"
                        },
                        new
                        {
                            CompetitionID = 2,
                            AdditionalTime = 5,
                            ArenaType = "Maniezas",
                            Article = "Art.238.2.1 ",
                            BreakTime = 10,
                            Class = "ATVIRA KLASĖ",
                            CompetitionType = "lentelė A",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2017),
                            Number = "3. ",
                            NumberOfJumps = 10,
                            NumberOfObstackles = 8,
                            Phase = 1,
                            PointsForExeedindTimeLimit = 1,
                            SecToStart = 45,
                            SheduledRunTime = 2,
                            TimeBeetweenRuns = 2,
                            Title = "Art.238.2.1 Konkūras pagal laiką, lentelė A"
                        },
                        new
                        {
                            CompetitionID = 3,
                            AdditionalTime = 5,
                            ArenaType = "Maniezas",
                            Article = "Art.238.2.1 ",
                            BreakTime = 10,
                            Class = "ATVIRA KLASĖ",
                            CompetitionType = "lentelė A",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2017),
                            Number = "5 ",
                            NumberOfJumps = 13,
                            NumberOfObstackles = 10,
                            Phase = 2,
                            PointsForExeedindTimeLimit = 1,
                            SecToStart = 45,
                            SheduledRunTime = 2,
                            TimeBeetweenRuns = 2,
                            Title = "Art.274.2.5 Dviejų fazių konkūras (Lentelė A, pagal laiką abejose fazėse"
                        });
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Entry", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AgreemntOnContractNr1")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HorseBirthYear")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HorseID")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<string>("HorseName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("NeedElectricity")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NeedInvoice")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfCages")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlateNumbers")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Points")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("RiderFullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RiderID")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Shavings")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StayFromDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StayToDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Time")
                        .HasMaxLength(50)
                        .HasColumnType("REAL");

                    b.Property<bool?>("Training")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryID");

                    b.HasIndex("CId");

                    b.HasIndex("UserId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            EntryID = 1,
                            AgreemntOnContractNr1 = true,
                            HorseID = 1,
                            HorseName = "The King",
                            NeedElectricity = false,
                            NeedInvoice = false,
                            NumberOfCages = 1,
                            PlateNumbers = "KEK:511",
                            Points = 0,
                            RiderFullName = "Linas Balciunas",
                            RiderID = 1,
                            Shavings = false,
                            Status = "Confirmed",
                            StayFromDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2022),
                            StayToDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2018),
                            Time = 0.0,
                            Training = false
                        },
                        new
                        {
                            EntryID = 2,
                            AgreemntOnContractNr1 = false,
                            HorseID = 2,
                            HorseName = "Perkunas",
                            NeedElectricity = false,
                            NeedInvoice = true,
                            NumberOfCages = 2,
                            PlateNumbers = "KEK:515",
                            Points = 0,
                            RiderFullName = "S Laurinaitis",
                            RiderID = 2,
                            Shavings = true,
                            Status = "Confirmed",
                            StayFromDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2022),
                            StayToDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2018),
                            Time = 0.0,
                            Training = false
                        },
                        new
                        {
                            EntryID = 3,
                            AgreemntOnContractNr1 = true,
                            HorseID = 3,
                            HorseName = "Nabagute",
                            NeedElectricity = true,
                            NeedInvoice = false,
                            NumberOfCages = 5,
                            PlateNumbers = "",
                            Points = 0,
                            RiderFullName = "Z Sarka",
                            RiderID = 3,
                            Shavings = false,
                            Status = "Confirmed",
                            StayFromDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2021),
                            StayToDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2017),
                            Time = 0.0,
                            Training = true
                        });
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organizer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Place")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("EventID");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventID = 1,
                            Country = "LT",
                            Currency = "Eur",
                            Organizer = "Harmony Park",
                            Place = "Vazgaikiemis",
                            Title = "LTU-3* Lietuvos Taurė I etapas"
                        },
                        new
                        {
                            EventID = 2,
                            Country = "LT",
                            Currency = "Eur",
                            Organizer = "Audruvis",
                            Place = "Joniškio raj.",
                            Title = "LTU-3* Audruvis Equistore 2 nd Birthday Cup "
                        },
                        new
                        {
                            EventID = 3,
                            Country = "LT",
                            Currency = "Eur",
                            Organizer = "Dargužiai",
                            Place = "Dargužiai",
                            Title = "CSI1*, CSIOJ, CSICh-A, CSIOCh, CSIP, CSIU25YJ-A"
                        });
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Horse", b =>
                {
                    b.Property<int>("HorseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Breeder")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChipNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Commets")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FEIID")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Father")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Heigth")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("HorseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MedCheckDate")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mother")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NatFedID")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PassportNoExipreDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("YearOfBird")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("HorseID");

                    b.HasIndex("UserId");

                    b.ToTable("Horses");

                    b.HasData(
                        new
                        {
                            HorseID = 1,
                            Breed = "Lietuvos sunkusis",
                            Color = "^irma",
                            Country = "LT",
                            Gender = "Kastratas",
                            HorseName = "Kingas",
                            OwnerName = "S. Laurinaitis",
                            YearOfBird = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1008)
                        },
                        new
                        {
                            HorseID = 2,
                            Breed = "Ristunas",
                            Color = "Juoda",
                            Country = "LT",
                            Gender = "Kastratas",
                            HorseName = "Perkūnas",
                            OwnerName = "S. Laurinaitis",
                            YearOfBird = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1009)
                        },
                        new
                        {
                            HorseID = 3,
                            Breed = "KWPN",
                            Breeder = "E.Onrust",
                            ChipNumber = "528003 06.06881",
                            Color = "Širma",
                            Country = "Olandija",
                            Father = "Silverstone",
                            Gender = "Kastratas",
                            HorseName = "Baltasar",
                            Mother = "Sally",
                            NatFedID = "1700034",
                            OwnerName = "Virginijus Praškevičius",
                            PassportNo = "528003 06.06881",
                            YearOfBird = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1972)
                        },
                        new
                        {
                            HorseID = 4,
                            Breed = "Zangersheide",
                            ChipNumber = "528003 06.06881",
                            Color = "Širma",
                            Country = "Belgija",
                            Father = "CORONAS",
                            Gender = "Eržilas",
                            HorseName = "Cassander Z",
                            Mother = "ANDIENA VH ASDONK ET Z",
                            NatFedID = "1700034",
                            OwnerName = "Valdas Urbonas",
                            PassportNo = "528003 06.06881",
                            YearOfBird = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1981)
                        },
                        new
                        {
                            HorseID = 5,
                            Breed = "Žemaitukai",
                            Breeder = "Stasys Svetlauskas",
                            Color = "Bėra",
                            Country = "Belgija",
                            Father = "Koralas",
                            Gender = "Kumelė",
                            HorseName = "Kamanė",
                            Mother = "Kražė",
                            NatFedID = "1700025",
                            OwnerName = "Ernesta Valaitienė",
                            PassportNo = "LTU003210052706",
                            YearOfBird = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2004)
                        },
                        new
                        {
                            HorseID = 6,
                            Breed = "Lietuvos jojamųjų",
                            Breeder = "Egidijus Civinskas",
                            Color = "Juodbėra",
                            Country = "Lietuva",
                            Father = "Laralee",
                            Gender = "Kastratas",
                            HorseName = "Kamanė",
                            Mother = "Ela",
                            NatFedID = "15444",
                            OwnerName = "Gabrielė Stasiulionytė",
                            PassportNo = "029272",
                            YearOfBird = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1987)
                        });
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WasOnline")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationID = 1,
                            Message = "Prasome atlikti Vet patikra",
                            Status = true,
                            Topic = "Vet Patikra"
                        },
                        new
                        {
                            NotificationID = 2,
                            Message = "Prasome atlikti Vet patikra",
                            Status = true,
                            Topic = "Vet Patikra"
                        },
                        new
                        {
                            NotificationID = 3,
                            Message = "Prasome atlikti Vet patikra",
                            Status = false,
                            Topic = "Vet Patikra"
                        },
                        new
                        {
                            NotificationID = 4,
                            Message = "Prasome patiklinti starto laika",
                            Status = false,
                            Topic = "Pakeistas Starto Laikas"
                        },
                        new
                        {
                            NotificationID = 5,
                            Message = "Prasome atlikti Vet patikra",
                            Status = true,
                            Topic = "Vet Patikra"
                        },
                        new
                        {
                            NotificationID = 6,
                            Message = "Prasome patiklinti starto laika",
                            Status = false,
                            Topic = "Pakeistas Starto Laikas"
                        },
                        new
                        {
                            NotificationID = 7,
                            Message = "Prasome patiklinti starto laika",
                            Status = false,
                            Topic = "Pakeistas Starto Laikas"
                        });
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Rider", b =>
                {
                    b.Property<int>("RiderID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FEIID")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InsuranceExiprationDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MedCheckDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NationalFederationID")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("RidersClubName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.HasKey("RiderID");

                    b.HasIndex("UserId");

                    b.ToTable("Riders");

                    b.HasData(
                        new
                        {
                            RiderID = 1,
                            Country = "LT",
                            FirstName = "Andrius",
                            LastName = "Petrovas"
                        },
                        new
                        {
                            RiderID = 2,
                            Country = "LT",
                            FirstName = "Matas",
                            LastName = "Petraitis"
                        },
                        new
                        {
                            RiderID = 3,
                            Country = "LT",
                            FirstName = "Kristupas",
                            LastName = "Petraitis"
                        },
                        new
                        {
                            RiderID = 4,
                            Country = "LT",
                            FirstName = "Nerijus",
                            LastName = "Šipaila"
                        },
                        new
                        {
                            RiderID = 5,
                            Country = "LT",
                            FirstName = "Kostas",
                            LastName = "Gaigalas"
                        },
                        new
                        {
                            RiderID = 6,
                            Country = "LT",
                            FirstName = "Laura",
                            LastName = "Martinavičiūtė"
                        },
                        new
                        {
                            RiderID = 7,
                            Country = "LT",
                            FirstName = "Danielius",
                            LastName = "Gutkauskas"
                        },
                        new
                        {
                            RiderID = 8,
                            Country = "LT",
                            FirstName = "Evita",
                            LastName = "Vismerytė"
                        },
                        new
                        {
                            RiderID = 9,
                            Country = "LT",
                            FirstName = "Karolina ",
                            LastName = "Vasiliauskaite"
                        });
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeiID")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalID")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("StaffID");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffID = 1,
                            Country = "LT",
                            FeiID = "FEI Level 1",
                            FirstName = "Marijonas",
                            Lastname = "Raila",
                            NationalID = "",
                            Position = "Ground Jury"
                        },
                        new
                        {
                            StaffID = 2,
                            Country = "LT",
                            FeiID = "",
                            FirstName = "Daiva",
                            Lastname = "Leonavičiūtė",
                            NationalID = "L3",
                            Position = "Jury"
                        },
                        new
                        {
                            StaffID = 3,
                            Country = "LT",
                            FeiID = "",
                            FirstName = "Ladas",
                            Lastname = "Katinas",
                            NationalID = "I NK",
                            Position = "Stuart"
                        });
                });

            modelBuilder.Entity("CompetitionStaff", b =>
                {
                    b.Property<int>("CompetitionsCompetitionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaffsStaffID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompetitionsCompetitionID", "StaffsStaffID");

                    b.HasIndex("StaffsStaffID");

                    b.ToTable("CompetionStaff", (string)null);
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Competition", b =>
                {
                    b.HasOne("CompetitionEventsManager.Models.Event", "Event")
                        .WithMany("Competitions")
                        .HasForeignKey("EId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Entry", b =>
                {
                    b.HasOne("CompetitionEventsManager.Models.Competition", "Competition")
                        .WithMany("Entries")
                        .HasForeignKey("CId");

                    b.HasOne("CompetitionEventsManager.Models.LocalUser", "LocalUser")
                        .WithMany("Entries")
                        .HasForeignKey("UserId");

                    b.Navigation("Competition");

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Horse", b =>
                {
                    b.HasOne("CompetitionEventsManager.Models.LocalUser", "LocalUser")
                        .WithMany("Horses")
                        .HasForeignKey("UserId");

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Notification", b =>
                {
                    b.HasOne("CompetitionEventsManager.Models.LocalUser", "LocalUser")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Rider", b =>
                {
                    b.HasOne("CompetitionEventsManager.Models.LocalUser", "LocalUser")
                        .WithMany("Riders")
                        .HasForeignKey("UserId");

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("CompetitionStaff", b =>
                {
                    b.HasOne("CompetitionEventsManager.Models.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionsCompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompetitionEventsManager.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffsStaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Competition", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.Event", b =>
                {
                    b.Navigation("Competitions");
                });

            modelBuilder.Entity("CompetitionEventsManager.Models.LocalUser", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Horses");

                    b.Navigation("Notifications");

                    b.Navigation("Riders");
                });
#pragma warning restore 612, 618
        }
    }
}
